- name: Restarting Grafana
  docker_compose:
    state: present
    restarted: true
    services:
      - grafana
    project_src: /home/{{ remote_user_name }}/docker

- name: Restarting Prometheus
  docker_compose:
    state: present
    restarted: true
    services:
      - prometheus
    project_src: /home/{{ remote_user_name }}/docker

- name: Restarting Nebula Monitors
  docker_compose:
    state: present
    restarted: true
    services: "nebula_monitor_{{ item.name }}"
    project_src: /home/{{ remote_user_name }}/docker
  with_items: "{{ networks }}"
