- name: Deploying SSH Public Key
  authorized_key:
    user: "{{ remote_user_name }}"
    key: "{{ ssh_public_key }}"
    state: present

- name: Enabling Public Key Authentication
#   become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PubkeyAuthentication\s+no'
    line: "PubkeyAuthentication yes"
    state: present
    backup: yes

- name: Disabling Password Authentication
#   become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PasswordAuthentication\s+yes'
    line: "PasswordAuthentication no"
    state: present
    backup: yes

# - name: Disabling root Login
# #   become: true
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     regexp: '^(#\s*)?PermitRootLogin\s+yes'
#     line: "PermitRootLogin no"
#     state: present
#     backup: yes

- name: Enabling TCP-Forwarding
  blockinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    validate: sshd -t -f %s
    block: |
      Match User {{ remote_user_name }}
        AllowTcpForwarding yes

- name: Checking SSH configuration
  become: yes
  command: sshd -t
  register: sshd_test
  failed_when: not ( sshd_test.rc == 0 )

- name: Restarting SSH
  service:
    name: ssh
    state: restarted
