apiVersion: 1
datasources:
 - name: Nebula Prometheus
   type: prometheus
   url: http://prometheus:9090
   isDefault: true
{% for network in networks %}
 - name: Postgres Nebula {{ network.name }}
   type: postgres
   url: postgres:5432
   user: nebula_{{ network.name }}_read
   database: nebula_{{ network.name }}
   jsonData:
     sslmode: disable
     postgresVersion: 13
   secureJsonData:
     password: {{ network.db_password_read }}
{% endfor %}
