---
- name: Setup Nebula Host
  hosts: root
  vars:
    ansible_user: root
  vars_files:
    - ansible.vault
  vars_prompt:
    - name: ssh_public_key
      prompt: "Please paste your SSH public key(s) [~/.ssh/id_rsa.pub] for user {{ remote_user_name }}"
      private: no
  tasks:
    - name: Changing root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"

    - name: Adding {{ remote_user_name }} and assign it to sudo group
      user:
        name: "{{ remote_user_name }}"
        password: "{{ remote_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/zsh
        append: yes
        state: present
        createhome: yes

    - name: Deploying SSH Public Key
      authorized_key:
        user: "{{ remote_user_name }}"
        key: "{{ ssh_public_key }}"
        state: present

    - name: Enabling Public Key Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(#\s*)?PubkeyAuthentication\s+no'
        line: "PubkeyAuthentication yes"
        state: present
        backup: yes

    - name: Checking SSH configuration
      become: yes
      command: sshd -t
      register: sshd_test
      failed_when: not ( sshd_test.rc == 0 )

    - name: Restarting SSH
      service:
        name: ssh
        state: restarted
